version: '3'

services:
  mongo:
    image: mongo:4.4.1
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
